using DevExpress.DataAccess.ConnectionParameters;
using DevExpress.DataAccess.Sql;
using DevExpress.DataProcessing.InMemoryDataProcessor;
using DevExpress.XtraEditors;
using DevExpress.XtraGrid.Views.Grid;
using DevExpress.XtraRichEdit.Model;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.SqlClient;
using System.Drawing;
using System.Linq;
using System.Reflection;
using System.Security.Cryptography;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using XCubeCrm.Common.Enums;
using XCubeCrm.UI.Win.Forms.BaseForms;
using XCubeCrm.UI.Win.Forms.BaseReport;
using XCubeCrm.UI.Win.Forms.UserControls.Controls.Grid;
using XCubeCrm.UI.Win.GenelForms;
using static DevExpress.XtraEditors.TextEdit;
using static System.Windows.Forms.VisualStyles.VisualStyleElement;

namespace XCubeCrm.UI.Win.Forms.Raporlar.Muhasebe
{
    public partial class KurFarkiHesaplama  : BaseReportListForm 
    {
        sqlBaglanti bgl = new sqlBaglanti();
        string araSorgu = "";
        public KurFarkiHesaplama( )
        {
 
            InitializeComponent();
        }
        protected override void Listele()
        {
            araSorgu = "";
            if (AnaForm.aktifKayilar != "")
            {
                araSorgu += "AND CLC.ACTIVE IN (" + AnaForm.aktifKayilar + ")";
            }
            if (AnaForm.cariLogicalref != "")
            {
                araSorgu += "AND CLC.LOGICALREF IN (" + AnaForm.cariLogicalref + ")";
            }
            if (AnaForm.ozelKod != "")
            {
                araSorgu += "AND CLC.SPECODE IN (" + AnaForm.ozelKod + ")";
            }
            if (AnaForm.ozelKod2 != "")
            {
                araSorgu += "AND CLC.SPECODE2 IN (" + AnaForm.ozelKod2 + ")";
            }
            if (AnaForm.ozelKod3 != "")
            {
                araSorgu += "AND CLC.SPECODE3 IN (" + AnaForm.ozelKod3 + ")";
            }
            if (AnaForm.ozelKod4 != "")
            {
                araSorgu += "AND CLC.SPECODE4 IN (" + AnaForm.ozelKod4 + ")";
            }
            if (AnaForm.ozelKod5 != "")
            {
                araSorgu += "AND CLC.SPECODE5 IN (" + AnaForm.ozelKod5 + ")";
            }
            if (AnaForm.yetkiKodu != "")
            {
                araSorgu += "AND CLC.CYPHCODE IN (" + AnaForm.yetkiKodu + ")";
            }
            if (AnaForm.dovizTuru != "")
            {
                araSorgu += "AND CLFL.TRCURR IN (" + AnaForm.dovizTuru + ")";
            }
            if (AnaForm.satisElemani != "")
            {
                araSorgu += " and CLC.LOGICALREF IN (" + " SELECT   LOGICALREF FROM ( " +
" SELECT LOGICALREF,   " +
" (SELECT TOP 1 SL.SALESMANREF FROM  " + AnaForm.db +  ".DBO.LG_" + AnaForm.firma +  "_SLSCLREL SL  " +
" JOIN " + AnaForm.db +  ".DBO.LG_SLSMAN  SLS ON SL.CLIENTREF=CLC.LOGICALREF AND SL.SALESMANREF = SLS.LOGICALREF AND SLS.FIRMNR =" + AnaForm.firma +  " ORDER BY  SL.LOGICALREF DESC ) AS SALESMANREF " +
" FROM " + AnaForm.db +  ".DBO.LG_" + AnaForm.firma +  "_CLCARD CLC " +
" ) AS AAA WHERE AAA.SALESMANREF IN ( " + AnaForm.satisElemani + "))";
            }
            string sorgu3 = " SELECT KOD,UNVAN " +
"   , MAX(DOVIZ) DOVIZ,ISNULL(MAX(DOVIZKUR), 0) KUR,CONVERT(DECIMAL(18, 4), MAX(DOLAR)) DOLARBAKIYE " +
"   ,CONVERT(DECIMAL(18, 4), MAX(DOLARTL)) DOLARTLBAKIYE " +
"   ,ISNULL(CONVERT(DECIMAL(18, 4), (MAX((DOLAR * DOVIZKUR) - ISNULL(DOLARTL, 0)))), 0)DOLARKURFARKI " +
"   ,MAX(EURO)EUROBAKIYE,MAX(EUROTL)EUROTLBAKIYE,ISNULL(MAX((EURO * DOVIZKUR) - ISNULL(EUROTL, 0)), 0)EUROKURFARKI " +
"   ,MAX(ALMAN_MARKI)ALMAN_MARKIBAKIYE,MAX(ALMAN_MARKI_TL)ALMAN_MARKI_TLBAKIYE,ISNULL(MAX((ALMAN_MARKI * DOVIZKUR) - ISNULL(ALMAN_MARKI_TL, 0)), 0)ALMAN_MARKI_FARKI ,   " +
" MAX(AVUSTRALYA_DOLARI)AVUSTRALYA_DOLARIBAKIYE,MAX(AVUSTRALYA_DOLARI_TL)AVUSTRALYA_DOLARI_TLBAKIYE,ISNULL(MAX((AVUSTRALYA_DOLARI * DOVIZKUR) - ISNULL(AVUSTRALYA_DOLARI_TL, 0)), 0)AVUSTRALYA_DOLARI_FARKI ,   " +
" MAX(AVUSTURYA_SILINI)AVUSTURYA_SILINIBAKIYE,MAX(AVUSTURYA_SILINI_TL)AVUSTURYA_SILINI_TLBAKIYE,ISNULL(MAX((AVUSTURYA_SILINI * DOVIZKUR) - ISNULL(AVUSTURYA_SILINI_TL, 0)), 0)AVUSTURYA_SILINI_FARKI ,   " +
" MAX(BELCIKA_FRANGI)BELCIKA_FRANGIBAKIYE,MAX(BELCIKA_FRANGI_TL)BELCIKA_FRANGI_TLBAKIYE,ISNULL(MAX((BELCIKA_FRANGI * DOVIZKUR) - ISNULL(BELCIKA_FRANGI_TL, 0)), 0)BELCIKA_FRANGI_FARKI ,   " +
" MAX(DANIMARKA_KRONU)DANIMARKA_KRONUBAKIYE,MAX(DANIMARKA_KRONU_TL)DANIMARKA_KRONU_TLBAKIYE,ISNULL(MAX((DANIMARKA_KRONU * DOVIZKUR) - ISNULL(DANIMARKA_KRONU_TL, 0)), 0)DANIMARKA_KRONU_FARKI ,   " +
" MAX(FIN_MARKKASI)FIN_MARKKASIBAKIYE,MAX(FIN_MARKKASI_TL)FIN_MARKKASI_TLBAKIYE,ISNULL(MAX((FIN_MARKKASI * DOVIZKUR) - ISNULL(FIN_MARKKASI_TL, 0)), 0)FIN_MARKKASI_FARKI ,   " +
" MAX(FRANSIZ_FRANGI)FRANSIZ_FRANGIBAKIYE,MAX(FRANSIZ_FRANGI_TL)FRANSIZ_FRANGI_TLBAKIYE,ISNULL(MAX((FRANSIZ_FRANGI * DOVIZKUR) - ISNULL(FRANSIZ_FRANGI_TL, 0)), 0)FRANSIZ_FRANGI_FARKI ,   " +
" MAX(HOLLANDA_FLORINI)HOLLANDA_FLORINIBAKIYE,MAX(HOLLANDA_FLORINI_TL)HOLLANDA_FLORINI_TLBAKIYE,ISNULL(MAX((HOLLANDA_FLORINI * DOVIZKUR) - ISNULL(HOLLANDA_FLORINI_TL, 0)), 0) HOLLANDA_FLORINI_FARKI ,   " +
" MAX(ISVEC_KRONU)ISVEC_KRONUBAKIYE,MAX(ISVEC_KRONU_TL)ISVEC_KRONU_TLBAKIYE,ISNULL(MAX((ISVEC_KRONU * DOVIZKUR) - ISNULL(ISVEC_KRONU_TL, 0)), 0) ISVEC_KRONU_FARKI ,   " +
" MAX(ISVICRE_FRANGI)ISVICRE_FRANGIBAKIYE,MAX(ISVICRE_FRANGI_TL)ISVICRE_FRANGI_TLBAKIYE,ISNULL(MAX((ISVICRE_FRANGI * DOVIZKUR) - ISNULL(ISVICRE_FRANGI_TL, 0)), 0)ISVICRE_FRANGI_FARKI ,   " +
" MAX(ITALYAN_LIRETI)ITALYAN_LIRETIBAKIYE,MAX(ITALYAN_LIRETI_TL)ITALYAN_LIRETI_TLBAKIYE,ISNULL(MAX((ITALYAN_LIRETI * DOVIZKUR) - ISNULL(ITALYAN_LIRETI_TL, 0)), 0)ITALYAN_LIRETI_FARKI ,   " +
" MAX(JAPON_YENI)JAPON_YENIBAKIYE,MAX(JAPON_YENI_TL)JAPON_YENI_TLBAKIYE,ISNULL(MAX((JAPON_YENI * DOVIZKUR) - ISNULL(JAPON_YENI_TL, 0)), 0)JAPON_YENI_FARKI ,   " +
" MAX(KANADA_DOLARI)KANADA_DOLARIBAKIYE,MAX(KANADA_DOLARI_TL)KANADA_DOLARI_TLBAKIYE,ISNULL(MAX((KANADA_DOLARI * DOVIZKUR) - ISNULL(KANADA_DOLARI_TL, 0)), 0)KANADA_DOLARI_FARKI ,   " +
" MAX(KUVEYT_DINARI)KUVEYT_DINARIBAKIYE,MAX(KUVEYT_DINARI_TL)KUVEYT_DINARI_TLBAKIYE,ISNULL(MAX((KUVEYT_DINARI * DOVIZKUR) - ISNULL(KUVEYT_DINARI_TL, 0)), 0)KUVEYT_DINARI_FARKI ,   " +
" MAX(NORVEC_KRONU)NORVEC_KRONUBAKIYE,MAX(NORVEC_KRONU_TL)NORVEC_KRONU_TLBAKIYE,ISNULL(MAX((NORVEC_KRONU * DOVIZKUR) - ISNULL(NORVEC_KRONU_TL, 0)), 0)NORVEC_KRONU_FARKI ,   " +
" MAX(INGILIZ_STERLINI)INGILIZ_STERLINIBAKIYE,MAX(INGILIZ_STERLINI_TL)INGILIZ_STERLINI_TLBAKIYE,ISNULL(MAX((INGILIZ_STERLINI * DOVIZKUR) - ISNULL(INGILIZ_STERLINI_TL, 0)), 0)INGILIZ_STERLINI_FARKI ,   " +
" MAX(S_ARABISTAN_RIYALI)S_ARABISTAN_RIYALIBAKIYE,MAX(S_ARABISTAN_RIYALI_TL)S_ARABISTAN_RIYALI_TLBAKIYE,ISNULL(MAX((S_ARABISTAN_RIYALI * DOVIZKUR) - ISNULL(S_ARABISTAN_RIYALI_TL, 0)), 0)S_ARABISTAN_RIYALI_FARKI ,   " +
" MAX(AVRUPA_PARA_BIRIMI)AVRUPA_PARA_BIRIMIBAKIYE,MAX(AVRUPA_PARA_BIRIMI_TL)AVRUPA_PARA_BIRIMI_TLBAKIYE,ISNULL(MAX((AVRUPA_PARA_BIRIMI * DOVIZKUR) - ISNULL(AVRUPA_PARA_BIRIMI_TL, 0)), 0)AVRUPA_PARA_BIRIMI_FARKI ,   " +
" MAX(AZERBAYCAN_MANATI)AZERBAYCAN_MANATIBAKIYE,MAX(AZERBAYCAN_MANATI_TL)AZERBAYCAN_MANATI_TLBAKIYE,ISNULL(MAX((AZERBAYCAN_MANATI * DOVIZKUR) - ISNULL(AZERBAYCAN_MANATI_TL, 0)), 0)AZERBAYCAN_MANATI_FARKI ,   " +
" MAX(BREZILYA_CRUZEIROSU)BREZILYA_CRUZEIROSUBAKIYE,MAX(BREZILYA_CRUZEIROSU_TL)BREZILYA_CRUZEIROSU_TLBAKIYE,ISNULL(MAX((BREZILYA_CRUZEIROSU * DOVIZKUR) - ISNULL(BREZILYA_CRUZEIROSU_TL, 0)), 0)BREZILYA_CRUZEIROSU_FARKI ,   " +
" MAX(BULGAR_LEVASI)BULGAR_LEVASIBAKIYE,MAX(BULGAR_LEVASI_TL)BULGAR_LEVASI_TLBAKIYE,ISNULL(MAX((BULGAR_LEVASI * DOVIZKUR) - ISNULL(BULGAR_LEVASI_TL, 0)), 0)BULGAR_LEVASI_FARKI ,   " +
" MAX(CEK_KURONU)CEK_KURONUBAKIYE,MAX(CEK_KURONU_TL)CEK_KURONU_TLBAKIYE,ISNULL(MAX((CEK_KURONU * DOVIZKUR) - ISNULL(CEK_KURONU_TL, 0)), 0)CEK_KURONU_FARKI ,   " +
" MAX(CIN_YUENI)CIN_YUENIBAKIYE,MAX(CIN_YUENI_TL)CIN_YUENI_TLBAKIYE,ISNULL(MAX((CIN_YUENI * DOVIZKUR) - ISNULL(CIN_YUENI_TL, 0)), 0)CIN_YUENI_FARKI ,   " +
" MAX(ESTONYA_KURONU)ESTONYA_KURONUBAKIYE,MAX(ESTONYA_KURONU_TL)ESTONYA_KURONU_TLBAKIYE,ISNULL(MAX((ESTONYA_KURONU * DOVIZKUR) - ISNULL(ESTONYA_KURONU_TL, 0)), 0)ESTONYA_KURONU_FARKI ,   " +
" MAX(GURCISTAN_LARISI)GURCISTAN_LARISIBAKIYE,MAX(GURCISTAN_LARISI_TL)GURCISTAN_LARISI_TLBAKIYE,ISNULL(MAX((GURCISTAN_LARISI * DOVIZKUR) - ISNULL(GURCISTAN_LARISI_TL, 0)), 0)GURCISTAN_LARISI_FARKI ,   " +
" MAX(HINDISTAN_RUPISI)HINDISTAN_RUPISIBAKIYE,MAX(HINDISTAN_RUPISI_TL)HINDISTAN_RUPISI_TLBAKIYE,ISNULL(MAX((HINDISTAN_RUPISI * DOVIZKUR) - ISNULL(HINDISTAN_RUPISI_TL, 0)), 0)HINDISTAN_RUPISI_FARKI ,   " +
" MAX(HONGKONG_DOLARI)HONGKONG_DOLARIBAKIYE,MAX(HONGKONG_DOLARI_TL)HONGKONG_DOLARI_TLBAKIYE,ISNULL(MAX((HONGKONG_DOLARI * DOVIZKUR) - ISNULL(HONGKONG_DOLARI_TL, 0)), 0)HONGKONG_DOLARI_FARKI ,   " +
" MAX(IRAK_DINARI)IRAK_DINARIBAKIYE,MAX(IRAK_DINARI_TL)IRAK_DINARI_TLBAKIYE,ISNULL(MAX((IRAK_DINARI * DOVIZKUR) - ISNULL(IRAK_DINARI_TL, 0)), 0)IRAK_DINARI_FARKI ,   " +
" MAX(IRAN_RIYALI)IRAN_RIYALIBAKIYE,MAX(IRAN_RIYALI_TL)IRAN_RIYALI_TLBAKIYE,ISNULL(MAX((IRAN_RIYALI * DOVIZKUR) - ISNULL(IRAN_RIYALI_TL, 0)), 0)IRAN_RIYALI_FARKI ,   " +
" MAX(IRLANDA_LIRASI)IRLANDA_LIRASIBAKIYE,MAX(IRLANDA_LIRASI_TL)IRLANDA_LIRASI_TLBAKIYE,ISNULL(MAX((IRLANDA_LIRASI * DOVIZKUR) - ISNULL(IRLANDA_LIRASI_TL, 0)), 0)IRLANDA_LIRASI_FARKI ,   " +
" MAX(ISPANYOL_PESETASI)ISPANYOL_PESETASIBAKIYE,MAX(ISPANYOL_PESETASI_TL)ISPANYOL_PESETASI_TLBAKIYE,ISNULL(MAX((ISPANYOL_PESETASI * DOVIZKUR) - ISNULL(ISPANYOL_PESETASI_TL, 0)), 0)ISPANYOL_PESETASI_FARKI ,   " +
" MAX(ISRAIL_SEKELI)ISRAIL_SEKELIBAKIYE,MAX(ISRAIL_SEKELI_TL)ISRAIL_SEKELI_TLBAKIYE,ISNULL(MAX((ISRAIL_SEKELI * DOVIZKUR) - ISNULL(ISRAIL_SEKELI_TL, 0)), 0)ISRAIL_SEKELI_FARKI ,   " +
" MAX(IZLANDA_KURONU)IZLANDA_KURONUBAKIYE,MAX(IZLANDA_KURONU_TL)IZLANDA_KURONU_TLBAKIYE,ISNULL(MAX((IZLANDA_KURONU * DOVIZKUR) - ISNULL(IZLANDA_KURONU_TL, 0)), 0)IZLANDA_KURONU_FARKI ,   " +
" MAX(KIBRIS_LIRASI)KIBRIS_LIRASIBAKIYE,MAX(KIBRIS_LIRASI_TL)KIBRIS_LIRASI_TLBAKIYE,ISNULL(MAX((KIBRIS_LIRASI * DOVIZKUR) - ISNULL(KIBRIS_LIRASI_TL, 0)), 0)KIBRIS_LIRASI_FARKI ,   " +
" MAX(KIRGIZISTAN_SOMU)KIRGIZISTAN_SOMUBAKIYE,MAX(KIRGIZISTAN_SOMU_TL)KIRGIZISTAN_SOMU_TLBAKIYE,ISNULL(MAX((KIRGIZISTAN_SOMU * DOVIZKUR) - ISNULL(KIRGIZISTAN_SOMU_TL, 0)), 0)KIRGIZISTAN_SOMU_FARKI ,   " +
" MAX(LETONYA_LATSI)LETONYA_LATSIBAKIYE,MAX(LETONYA_LATSI_TL)LETONYA_LATSI_TLBAKIYE,ISNULL(MAX((LETONYA_LATSI * DOVIZKUR) - ISNULL(LETONYA_LATSI_TL, 0)), 0)LETONYA_LATSI_FARKI ,   " +
" MAX(LIBYA_DINARI)LIBYA_DINARIBAKIYE,MAX(LIBYA_DINARI_TL)LIBYA_DINARI_TLBAKIYE,ISNULL(MAX((LIBYA_DINARI * DOVIZKUR) - ISNULL(LIBYA_DINARI_TL, 0)), 0)LIBYA_DINARI_FARKI ,   " +
" MAX(LUBNAN_LIRASI)LUBNAN_LIRASIBAKIYE,MAX(LUBNAN_LIRASI_TL)LUBNAN_LIRASI_TLBAKIYE,ISNULL(MAX((LUBNAN_LIRASI * DOVIZKUR) - ISNULL(LUBNAN_LIRASI_TL, 0)), 0)LUBNAN_LIRASI_FARKI ,   " +
" MAX(LITVANYA_LITASI)LITVANYA_LITASIBAKIYE,MAX(LITVANYA_LITASI_TL)LITVANYA_LITASI_TLBAKIYE,ISNULL(MAX((LITVANYA_LITASI * DOVIZKUR) - ISNULL(LITVANYA_LITASI_TL, 0)), 0)LITVANYA_LITASI_FARKI ,   " +
" MAX(LUKSEMBURG_FRANGI)LUKSEMBURG_FRANGIBAKIYE,MAX(LUKSEMBURG_FRANGI_TL)LUKSEMBURG_FRANGI_TLBAKIYE,ISNULL(MAX((LUKSEMBURG_FRANGI * DOVIZKUR) - ISNULL(LUKSEMBURG_FRANGI_TL, 0)), 0)LUKSEMBURG_FRANGI_FARKI ,   " +
" MAX(MACARISTAN_FORINTI)MACARISTAN_FORINTIBAKIYE,MAX(MACARISTAN_FORINTI_TL)MACARISTAN_FORINTI_TLBAKIYE,ISNULL(MAX((MACARISTAN_FORINTI * DOVIZKUR) - ISNULL(MACARISTAN_FORINTI_TL, 0)), 0)MACARISTAN_FORINTI_FARKI ,   " +
" MAX(MALEZYA_RINGGITI)MALEZYA_RINGGITIBAKIYE,MAX(MALEZYA_RINGGITI_TL)MALEZYA_RINGGITI_TLBAKIYE,ISNULL(MAX((MALEZYA_RINGGITI * DOVIZKUR) - ISNULL(MALEZYA_RINGGITI_TL, 0)), 0)MALEZYA_RINGGITI_FARKI ,   " +
" MAX(MEKSIKA_PESOSU)MEKSIKA_PESOSUBAKIYE,MAX(MEKSIKA_PESOSU_TL)MEKSIKA_PESOSU_TLBAKIYE,ISNULL(MAX((MEKSIKA_PESOSU * DOVIZKUR) - ISNULL(MEKSIKA_PESOSU_TL, 0)), 0)MEKSIKA_PESOSU_FARKI ,   " +
" MAX(MISIR_LIRASI)MISIR_LIRASIBAKIYE,MAX(MISIR_LIRASI_TL)MISIR_LIRASI_TLBAKIYE,ISNULL(MAX((MISIR_LIRASI * DOVIZKUR) - ISNULL(MISIR_LIRASI_TL, 0)), 0)MISIR_LIRASI_FARKI ,   " +
" MAX(BARBADOS_DOLARI)BARBADOS_DOLARIBAKIYE,MAX(BARBADOS_DOLARI_TL)BARBADOS_DOLARI_TLBAKIYE,ISNULL(MAX((BARBADOS_DOLARI * DOVIZKUR) - ISNULL(BARBADOS_DOLARI_TL, 0)), 0)BARBADOS_DOLARI_FARKI ,   " +
" MAX(POLONYA_ZLOTISI)POLONYA_ZLOTISIBAKIYE,MAX(POLONYA_ZLOTISI_TL)POLONYA_ZLOTISI_TLBAKIYE,ISNULL(MAX((POLONYA_ZLOTISI * DOVIZKUR) - ISNULL(POLONYA_ZLOTISI_TL, 0)), 0)POLONYA_ZLOTISI_FARKI ,   " +
" MAX(PORTEKIZ_ESCUDOSU)PORTEKIZ_ESCUDOSUBAKIYE,MAX(PORTEKIZ_ESCUDOSU_TL)PORTEKIZ_ESCUDOSU_TLBAKIYE,ISNULL(MAX((PORTEKIZ_ESCUDOSU * DOVIZKUR) - ISNULL(PORTEKIZ_ESCUDOSU_TL, 0)), 0)PORTEKIZ_ESCUDOSU_FARKI ,   " +
" MAX(ROMEN_LEYI)ROMEN_LEYIBAKIYE,MAX(ROMEN_LEYI_TL)ROMEN_LEYI_TLBAKIYE,ISNULL(MAX((ROMEN_LEYI * DOVIZKUR) - ISNULL(ROMEN_LEYI_TL, 0)), 0)ROMEN_LEYI_FARKI ,   " +
" MAX(RUS_RUBLESI)RUS_RUBLESIBAKIYE,MAX(RUS_RUBLESI_TL)RUS_RUBLESI_TLBAKIYE,ISNULL(MAX((RUS_RUBLESI * DOVIZKUR) - ISNULL(RUS_RUBLESI_TL, 0)), 0)RUS_RUBLESI_FARKI ,   " +
" MAX(TAYVAN_DOLARI)TAYVAN_DOLARIBAKIYE,MAX(TAYVAN_DOLARI_TL)TAYVAN_DOLARI_TLBAKIYE,ISNULL(MAX((TAYVAN_DOLARI * DOVIZKUR) - ISNULL(TAYVAN_DOLARI_TL, 0)), 0)TAYVAN_DOLARI_FARKI ,   " +
" MAX(TURK_LIRASI)TURK_LIRASIBAKIYE,MAX(TURK_LIRASI_TL)TURK_LIRASI_TLBAKIYE,ISNULL(MAX((TURK_LIRASI * DOVIZKUR) - ISNULL(TURK_LIRASI_TL, 0)), 0)TURK_LIRASI_FARKI ,   " +
" MAX(URDUN_DINARI)URDUN_DINARIBAKIYE,MAX(URDUN_DINARI_TL)URDUN_DINARI_TLBAKIYE,ISNULL(MAX((URDUN_DINARI * DOVIZKUR) - ISNULL(URDUN_DINARI_TL, 0)), 0)URDUN_DINARI_FARKI ,   " +
" MAX(YUNAN_DRAHMISI)YUNAN_DRAHMISIBAKIYE,MAX(YUNAN_DRAHMISI_TL)YUNAN_DRAHMISI_TLBAKIYE,ISNULL(MAX((YUNAN_DRAHMISI * DOVIZKUR) - ISNULL(YUNAN_DRAHMISI_TL, 0)), 0)YUNAN_DRAHMISI_FARKI ,   " +
" MAX(ARJANTIN_PESOSU)ARJANTIN_PESOSUBAKIYE,MAX(ARJANTIN_PESOSU_TL)ARJANTIN_PESOSU_TLBAKIYE,ISNULL(MAX((ARJANTIN_PESOSU * DOVIZKUR) - ISNULL(ARJANTIN_PESOSU_TL, 0)), 0)ARJANTIN_PESOSU_FARKI ,   " +
" MAX(LAOS_KIPI)LAOS_KIPIBAKIYE,MAX(LAOS_KIPI_TL)LAOS_KIPI_TLBAKIYE,ISNULL(MAX((LAOS_KIPI * DOVIZKUR) - ISNULL(LAOS_KIPI_TL, 0)), 0)LAOS_KIPI_FARKI ,   " +
" MAX(ANDORRA_PESETASI)ANDORRA_PESETASIBAKIYE,MAX(ANDORRA_PESETASI_TL)ANDORRA_PESETASI_TLBAKIYE,ISNULL(MAX((ANDORRA_PESETASI * DOVIZKUR) - ISNULL(ANDORRA_PESETASI_TL, 0)), 0)ANDORRA_PESETASI_FARKI ,   " +
" MAX(BAE_DIRHEMI)BAE_DIRHEMIBAKIYE,MAX(BAE_DIRHEMI_TL)BAE_DIRHEMI_TLBAKIYE,ISNULL(MAX((BAE_DIRHEMI * DOVIZKUR) - ISNULL(BAE_DIRHEMI_TL, 0)), 0)BAE_DIRHEMI_FARKI ,   " +
" MAX(AFGANISTAN_AFGANISI)AFGANISTAN_AFGANISIBAKIYE,MAX(AFGANISTAN_AFGANISI_TL)AFGANISTAN_AFGANISI_TLBAKIYE,ISNULL(MAX((AFGANISTAN_AFGANISI * DOVIZKUR) - ISNULL(AFGANISTAN_AFGANISI_TL, 0)), 0)AFGANISTAN_AFGANISI_FARKI ,   " +
" MAX(ARNAVUTLUK_LEKI)ARNAVUTLUK_LEKIBAKIYE,MAX(ARNAVUTLUK_LEKI_TL)ARNAVUTLUK_LEKI_TLBAKIYE,ISNULL(MAX((ARNAVUTLUK_LEKI * DOVIZKUR) - ISNULL(ARNAVUTLUK_LEKI_TL, 0)), 0)ARNAVUTLUK_LEKI_FARKI ,   " +
" MAX(HOLLANDA_ANTILLERI_FLORINI)HOLLANDA_ANTILLERI_FLORINIBAKIYE,MAX(HOLLANDA_ANTILLERI_FLORINI_TL)HOLLANDA_ANTILLERI_FLORINI_TLBAKIYE,ISNULL(MAX((HOLLANDA_ANTILLERI_FLORINI * DOVIZKUR) - ISNULL(HOLLANDA_ANTILLERI_FLORINI_TL, 0)), 0)HOLLANDA_ANTILLERI_FLORINI_FARKI ,   " +
" MAX(ANGOLA_KWANZASI)ANGOLA_KWANZASIBAKIYE,MAX(ANGOLA_KWANZASI_TL)ANGOLA_KWANZASI_TLBAKIYE,ISNULL(MAX((ANGOLA_KWANZASI * DOVIZKUR) - ISNULL(ANGOLA_KWANZASI_TL, 0)), 0)ANGOLA_KWANZASI_FARKI ,   " +
" MAX(BENGALDES_TAKASI)BENGALDES_TAKASIBAKIYE,MAX(BENGALDES_TAKASI_TL)BENGALDES_TAKASI_TLBAKIYE,ISNULL(MAX((BENGALDES_TAKASI * DOVIZKUR) - ISNULL(BENGALDES_TAKASI_TL, 0)), 0)BENGALDES_TAKASI_FARKI ,   " +
" MAX(BAHREYN_DINARI)BAHREYN_DINARIBAKIYE,MAX(BAHREYN_DINARI_TL)BAHREYN_DINARI_TLBAKIYE,ISNULL(MAX((BAHREYN_DINARI * DOVIZKUR) - ISNULL(BAHREYN_DINARI_TL, 0)), 0)BAHREYN_DINARI_FARKI ,   " +
" MAX(BURUNDI_FRANGI)BURUNDI_FRANGIBAKIYE,MAX(BURUNDI_FRANGI_TL)BURUNDI_FRANGI_TLBAKIYE,ISNULL(MAX((BURUNDI_FRANGI * DOVIZKUR) - ISNULL(BURUNDI_FRANGI_TL, 0)), 0)BURUNDI_FRANGI_FARKI ,   " +
" MAX(BERMUDA_DOLARI)BERMUDA_DOLARIBAKIYE,MAX(BERMUDA_DOLARI_TL)BERMUDA_DOLARI_TLBAKIYE,ISNULL(MAX((BERMUDA_DOLARI * DOVIZKUR) - ISNULL(BERMUDA_DOLARI_TL, 0)), 0)BERMUDA_DOLARI_FARKI ,   " +
" MAX(BRUNEI_DOLARI)BRUNEI_DOLARIBAKIYE,MAX(BRUNEI_DOLARI_TL)BRUNEI_DOLARI_TLBAKIYE,ISNULL(MAX((BRUNEI_DOLARI * DOVIZKUR) - ISNULL(BRUNEI_DOLARI_TL, 0)), 0)BRUNEI_DOLARI_FARKI ,   " +
" MAX(BOLIVYA_BOLIVIANOSU)BOLIVYA_BOLIVIANOSUBAKIYE,MAX(BOLIVYA_BOLIVIANOSU_TL)BOLIVYA_BOLIVIANOSU_TLBAKIYE,ISNULL(MAX((BOLIVYA_BOLIVIANOSU * DOVIZKUR) - ISNULL(BOLIVYA_BOLIVIANOSU_TL, 0)), 0)BOLIVYA_BOLIVIANOSU_FARKI ,   " +
" MAX(BAHAMA_DOLARI)BAHAMA_DOLARIBAKIYE,MAX(BAHAMA_DOLARI_TL)BAHAMA_DOLARI_TLBAKIYE,ISNULL(MAX((BAHAMA_DOLARI * DOVIZKUR) - ISNULL(BAHAMA_DOLARI_TL, 0)), 0)BAHAMA_DOLARI_FARKI ,   " +
" MAX(BUTAN_LIRASI)BUTAN_LIRASIBAKIYE,MAX(BUTAN_LIRASI_TL)BUTAN_LIRASI_TLBAKIYE,ISNULL(MAX((BUTAN_LIRASI * DOVIZKUR) - ISNULL(BUTAN_LIRASI_TL, 0)), 0)BUTAN_LIRASI_FARKI ,   " +
" MAX(BOTSWANA_PULASI)BOTSWANA_PULASIBAKIYE,MAX(BOTSWANA_PULASI_TL)BOTSWANA_PULASI_TLBAKIYE,ISNULL(MAX((BOTSWANA_PULASI * DOVIZKUR) - ISNULL(BOTSWANA_PULASI_TL, 0)), 0)BOTSWANA_PULASI_FARKI ,   " +
" MAX(BELIZE_DOLARI)BELIZE_DOLARIBAKIYE,MAX(BELIZE_DOLARI_TL)BELIZE_DOLARI_TLBAKIYE,ISNULL(MAX((BELIZE_DOLARI * DOVIZKUR) - ISNULL(BELIZE_DOLARI_TL, 0)), 0)BELIZE_DOLARI_FARKI ,   " +
" MAX(SILI_PESOSU)SILI_PESOSUBAKIYE,MAX(SILI_PESOSU_TL)SILI_PESOSU_TLBAKIYE,ISNULL(MAX((SILI_PESOSU * DOVIZKUR) - ISNULL(SILI_PESOSU_TL, 0)), 0)SILI_PESOSU_FARKI ,   " +
" MAX(KOLOMBIYA_PESOSU)KOLOMBIYA_PESOSUBAKIYE,MAX(KOLOMBIYA_PESOSU_TL)KOLOMBIYA_PESOSU_TLBAKIYE,ISNULL(MAX((KOLOMBIYA_PESOSU * DOVIZKUR) - ISNULL(KOLOMBIYA_PESOSU_TL, 0)), 0)KOLOMBIYA_PESOSU_FARKI ,   " +
" MAX(KOSTA_RIKA_KOLONU)KOSTA_RIKA_KOLONUBAKIYE,MAX(KOSTA_RIKA_KOLONU_TL)KOSTA_RIKA_KOLONU_TLBAKIYE,ISNULL(MAX((KOSTA_RIKA_KOLONU * DOVIZKUR) - ISNULL(KOSTA_RIKA_KOLONU_TL, 0)), 0)KOSTA_RIKA_KOLONU_FARKI ,   " +
" MAX(KUBA_PESOSU)KUBA_PESOSUBAKIYE,MAX(KUBA_PESOSU_TL)KUBA_PESOSU_TLBAKIYE,ISNULL(MAX((KUBA_PESOSU * DOVIZKUR) - ISNULL(KUBA_PESOSU_TL, 0)), 0)KUBA_PESOSU_FARKI ,   " +
" MAX(CAPE_VERDE_ESKUDOSU)CAPE_VERDE_ESKUDOSUBAKIYE,MAX(CAPE_VERDE_ESKUDOSU_TL)CAPE_VERDE_ESKUDOSU_TLBAKIYE,ISNULL(MAX((CAPE_VERDE_ESKUDOSU * DOVIZKUR) - ISNULL(CAPE_VERDE_ESKUDOSU_TL, 0)), 0)CAPE_VERDE_ESKUDOSU_FARKI ,   " +
" MAX(CIBUTI_FRANGI)CIBUTI_FRANGIBAKIYE,MAX(CIBUTI_FRANGI_TL)CIBUTI_FRANGI_TLBAKIYE,ISNULL(MAX((CIBUTI_FRANGI * DOVIZKUR) - ISNULL(CIBUTI_FRANGI_TL, 0)), 0)CIBUTI_FRANGI_FARKI ,   " +
" MAX(DOMINIK_PESOSU)DOMINIK_PESOSUBAKIYE,MAX(DOMINIK_PESOSU_TL)DOMINIK_PESOSU_TLBAKIYE,ISNULL(MAX((DOMINIK_PESOSU * DOVIZKUR) - ISNULL(DOMINIK_PESOSU_TL, 0)), 0)DOMINIK_PESOSU_FARKI ,   " +
" MAX(CEZAYIR_DINARI)CEZAYIR_DINARIBAKIYE,MAX(CEZAYIR_DINARI_TL)CEZAYIR_DINARI_TLBAKIYE,ISNULL(MAX((CEZAYIR_DINARI * DOVIZKUR) - ISNULL(CEZAYIR_DINARI_TL, 0)), 0)CEZAYIR_DINARI_FARKI ,   " +
" MAX(EKVATOR_SUCRESI)EKVATOR_SUCRESIBAKIYE,MAX(EKVATOR_SUCRESI_TL)EKVATOR_SUCRESI_TLBAKIYE,ISNULL(MAX((EKVATOR_SUCRESI * DOVIZKUR) - ISNULL(EKVATOR_SUCRESI_TL, 0)), 0)EKVATOR_SUCRESI_FARKI ,   " +
" MAX(ETYOPYA_BIRRI)ETYOPYA_BIRRIBAKIYE,MAX(ETYOPYA_BIRRI_TL)ETYOPYA_BIRRI_TLBAKIYE,ISNULL(MAX((ETYOPYA_BIRRI * DOVIZKUR) - ISNULL(ETYOPYA_BIRRI_TL, 0)), 0)ETYOPYA_BIRRI_FARKI ,   " +
" MAX(FIJI_ADALARI_DOLARI)FIJI_ADALARI_DOLARIBAKIYE,MAX(FIJI_ADALARI_DOLARI_TL)FIJI_ADALARI_DOLARI_TLBAKIYE,ISNULL(MAX((FIJI_ADALARI_DOLARI * DOVIZKUR) - ISNULL(FIJI_ADALARI_DOLARI_TL, 0)), 0)FIJI_ADALARI_DOLARI_FARKI ,   " +
" MAX(FALKLAND_ADALARI_STERLINI)FALKLAND_ADALARI_STERLINIBAKIYE,MAX(FALKLAND_ADALARI_STERLINI_TL)FALKLAND_ADALARI_STERLINI_TLBAKIYE,ISNULL(MAX((FALKLAND_ADALARI_STERLINI * DOVIZKUR) - ISNULL(FALKLAND_ADALARI_STERLINI_TL, 0)), 0)FALKLAND_ADALARI_STERLINI_FARKI ,   " +
" MAX(GANA_CEDISI)GANA_CEDISIBAKIYE,MAX(GANA_CEDISI_TL)GANA_CEDISI_TLBAKIYE,ISNULL(MAX((GANA_CEDISI * DOVIZKUR) - ISNULL(GANA_CEDISI_TL, 0)), 0)GANA_CEDISI_FARKI ,   " +
" MAX(CEBELITARIK_STERLINI)CEBELITARIK_STERLINIBAKIYE,MAX(CEBELITARIK_STERLINI_TL)CEBELITARIK_STERLINI_TLBAKIYE,ISNULL(MAX((CEBELITARIK_STERLINI * DOVIZKUR) - ISNULL(CEBELITARIK_STERLINI_TL, 0)), 0)CEBELITARIK_STERLINI_FARKI ,   " +
" MAX(GAMBIA_DALASISI)GAMBIA_DALASISIBAKIYE,MAX(GAMBIA_DALASISI_TL)GAMBIA_DALASISI_TLBAKIYE,ISNULL(MAX((GAMBIA_DALASISI * DOVIZKUR) - ISNULL(GAMBIA_DALASISI_TL, 0)), 0)GAMBIA_DALASISI_FARKI ,   " +
" MAX(GINE_FRANGI)GINE_FRANGIBAKIYE,MAX(GINE_FRANGI_TL)GINE_FRANGI_TLBAKIYE,ISNULL(MAX((GINE_FRANGI * DOVIZKUR) - ISNULL(GINE_FRANGI_TL, 0)), 0)GINE_FRANGI_FARKI ,   " +
" MAX(GUATEMALA_QUETZALI)GUATEMALA_QUETZALIBAKIYE,MAX(GUATEMALA_QUETZALI_TL)GUATEMALA_QUETZALI_TLBAKIYE,ISNULL(MAX((GUATEMALA_QUETZALI * DOVIZKUR) - ISNULL(GUATEMALA_QUETZALI_TL, 0)), 0)GUATEMALA_QUETZALI_FARKI ,   " +
" MAX(GINEBISSE_PESOSU)GINEBISSE_PESOSUBAKIYE,MAX(GINEBISSE_PESOSU_TL)GINEBISSE_PESOSU_TLBAKIYE,ISNULL(MAX((GINEBISSE_PESOSU * DOVIZKUR) - ISNULL(GINEBISSE_PESOSU_TL, 0)), 0)GINEBISSE_PESOSU_FARKI ,   " +
" MAX(GUYANA_DOLARI)GUYANA_DOLARIBAKIYE,MAX(GUYANA_DOLARI_TL)GUYANA_DOLARI_TLBAKIYE,ISNULL(MAX((GUYANA_DOLARI * DOVIZKUR) - ISNULL(GUYANA_DOLARI_TL, 0)), 0)GUYANA_DOLARI_FARKI ,   " +
" MAX(HONDURAS_LEMPIRASI)HONDURAS_LEMPIRASIBAKIYE,MAX(HONDURAS_LEMPIRASI_TL)HONDURAS_LEMPIRASI_TLBAKIYE,ISNULL(MAX((HONDURAS_LEMPIRASI * DOVIZKUR) - ISNULL(HONDURAS_LEMPIRASI_TL, 0)), 0)HONDURAS_LEMPIRASI_FARKI ,   " +
" MAX(HAITI_GOURDESI)HAITI_GOURDESIBAKIYE,MAX(HAITI_GOURDESI_TL)HAITI_GOURDESI_TLBAKIYE,ISNULL(MAX((HAITI_GOURDESI * DOVIZKUR) - ISNULL(HAITI_GOURDESI_TL, 0)), 0)HAITI_GOURDESI_FARKI ,   " +
" MAX(ENDONEZYA_RUPISI)ENDONEZYA_RUPISIBAKIYE,MAX(ENDONEZYA_RUPISI_TL)ENDONEZYA_RUPISI_TLBAKIYE,ISNULL(MAX((ENDONEZYA_RUPISI * DOVIZKUR) - ISNULL(ENDONEZYA_RUPISI_TL, 0)), 0)ENDONEZYA_RUPISI_FARKI ,   " +
" MAX(JAMAIKA_DOLARI)JAMAIKA_DOLARIBAKIYE,MAX(JAMAIKA_DOLARI_TL)JAMAIKA_DOLARI_TLBAKIYE,ISNULL(MAX((JAMAIKA_DOLARI * DOVIZKUR) - ISNULL(JAMAIKA_DOLARI_TL, 0)), 0)JAMAIKA_DOLARI_FARKI ,   " +
" MAX(KENYA_SILINGI)KENYA_SILINGIBAKIYE,MAX(KENYA_SILINGI_TL)KENYA_SILINGI_TLBAKIYE,ISNULL(MAX((KENYA_SILINGI * DOVIZKUR) - ISNULL(KENYA_SILINGI_TL, 0)), 0)KENYA_SILINGI_FARKI ,   " +
" MAX(KAMBOCYA_RIELI)KAMBOCYA_RIELIBAKIYE,MAX(KAMBOCYA_RIELI_TL)KAMBOCYA_RIELI_TLBAKIYE,ISNULL(MAX((KAMBOCYA_RIELI * DOVIZKUR) - ISNULL(KAMBOCYA_RIELI_TL, 0)), 0)KAMBOCYA_RIELI_FARKI ,   " +
" MAX(KOMOR_FRANGI)KOMOR_FRANGIBAKIYE,MAX(KOMOR_FRANGI_TL)KOMOR_FRANGI_TLBAKIYE,ISNULL(MAX((KOMOR_FRANGI * DOVIZKUR) - ISNULL(KOMOR_FRANGI_TL, 0)), 0)KOMOR_FRANGI_FARKI ,   " +
" MAX(KUZEY_KORE_WONU)KUZEY_KORE_WONUBAKIYE,MAX(KUZEY_KORE_WONU_TL)KUZEY_KORE_WONU_TLBAKIYE,ISNULL(MAX((KUZEY_KORE_WONU * DOVIZKUR) - ISNULL(KUZEY_KORE_WONU_TL, 0)), 0)KUZEY_KORE_WONU_FARKI ,   " +
" MAX(GUNEY_KORE_WONU)GUNEY_KORE_WONUBAKIYE,MAX(GUNEY_KORE_WONU_TL)GUNEY_KORE_WONU_TLBAKIYE,ISNULL(MAX((GUNEY_KORE_WONU * DOVIZKUR) - ISNULL(GUNEY_KORE_WONU_TL, 0)), 0)GUNEY_KORE_WONU_FARKI ,   " +
" MAX(CAYMAN_ADALARI_DOLARI)CAYMAN_ADALARI_DOLARIBAKIYE,MAX(CAYMAN_ADALARI_DOLARI_TL)CAYMAN_ADALARI_DOLARI_TLBAKIYE,ISNULL(MAX((CAYMAN_ADALARI_DOLARI * DOVIZKUR) - ISNULL(CAYMAN_ADALARI_DOLARI_TL, 0)), 0)CAYMAN_ADALARI_DOLARI_FARKI ,   " +
" MAX(SRI_LANKA_RUPISI)SRI_LANKA_RUPISIBAKIYE,MAX(SRI_LANKA_RUPISI_TL)SRI_LANKA_RUPISI_TLBAKIYE,ISNULL(MAX((SRI_LANKA_RUPISI * DOVIZKUR) - ISNULL(SRI_LANKA_RUPISI_TL, 0)), 0)SRI_LANKA_RUPISI_FARKI ,   " +
" MAX(LIBERYA_DOLARI)LIBERYA_DOLARIBAKIYE,MAX(LIBERYA_DOLARI_TL)LIBERYA_DOLARI_TLBAKIYE,ISNULL(MAX((LIBERYA_DOLARI * DOVIZKUR) - ISNULL(LIBERYA_DOLARI_TL, 0)), 0)LIBERYA_DOLARI_FARKI ,   " +
" MAX(LESOTO_LOTISI)LESOTO_LOTISIBAKIYE,MAX(LESOTO_LOTISI_TL)LESOTO_LOTISI_TLBAKIYE,ISNULL(MAX((LESOTO_LOTISI * DOVIZKUR) - ISNULL(LESOTO_LOTISI_TL, 0)), 0)LESOTO_LOTISI_FARKI ,   " +
" MAX(FAS_DIRHEMI)FAS_DIRHEMIBAKIYE,MAX(FAS_DIRHEMI_TL)FAS_DIRHEMI_TLBAKIYE,ISNULL(MAX((FAS_DIRHEMI * DOVIZKUR) - ISNULL(FAS_DIRHEMI_TL, 0)), 0)FAS_DIRHEMI_FARKI ,   " +
" MAX(MOGOL_TUGRIKI)MOGOL_TUGRIKIBAKIYE,MAX(MOGOL_TUGRIKI_TL)MOGOL_TUGRIKI_TLBAKIYE,ISNULL(MAX((MOGOL_TUGRIKI * DOVIZKUR) - ISNULL(MOGOL_TUGRIKI_TL, 0)), 0)MOGOL_TUGRIKI_FARKI ,   " +
" MAX(MACAU_PATACASI)MACAU_PATACASIBAKIYE,MAX(MACAU_PATACASI_TL)MACAU_PATACASI_TLBAKIYE,ISNULL(MAX((MACAU_PATACASI * DOVIZKUR) - ISNULL(MACAU_PATACASI_TL, 0)), 0)MACAU_PATACASI_FARKI ,   " +
" MAX(MORITANYA_OGIYASI)MORITANYA_OGIYASIBAKIYE,MAX(MORITANYA_OGIYASI_TL)MORITANYA_OGIYASI_TLBAKIYE,ISNULL(MAX((MORITANYA_OGIYASI * DOVIZKUR) - ISNULL(MORITANYA_OGIYASI_TL, 0)), 0)MORITANYA_OGIYASI_FARKI ,   " +
" MAX(MALTA_LIRASI)MALTA_LIRASIBAKIYE,MAX(MALTA_LIRASI_TL)MALTA_LIRASI_TLBAKIYE,ISNULL(MAX((MALTA_LIRASI * DOVIZKUR) - ISNULL(MALTA_LIRASI_TL, 0)), 0)MALTA_LIRASI_FARKI ,   " +
" MAX(MAURITIUS_RUPISI)MAURITIUS_RUPISIBAKIYE,MAX(MAURITIUS_RUPISI_TL)MAURITIUS_RUPISI_TLBAKIYE,ISNULL(MAX((MAURITIUS_RUPISI * DOVIZKUR) - ISNULL(MAURITIUS_RUPISI_TL, 0)), 0)MAURITIUS_RUPISI_FARKI ,   " +
" MAX(MALDIV_RUFIYASI)MALDIV_RUFIYASIBAKIYE,MAX(MALDIV_RUFIYASI_TL)MALDIV_RUFIYASI_TLBAKIYE,ISNULL(MAX((MALDIV_RUFIYASI * DOVIZKUR) - ISNULL(MALDIV_RUFIYASI_TL, 0)), 0)MALDIV_RUFIYASI_FARKI ,   " +
" MAX(MALAVI_KWACHASI)MALAVI_KWACHASIBAKIYE,MAX(MALAVI_KWACHASI_TL)MALAVI_KWACHASI_TLBAKIYE,ISNULL(MAX((MALAVI_KWACHASI * DOVIZKUR) - ISNULL(MALAVI_KWACHASI_TL, 0)), 0)MALAVI_KWACHASI_FARKI ,   " +
" MAX(MOZAMBIK_METICALI)MOZAMBIK_METICALIBAKIYE,MAX(MOZAMBIK_METICALI_TL)MOZAMBIK_METICALI_TLBAKIYE,ISNULL(MAX((MOZAMBIK_METICALI * DOVIZKUR) - ISNULL(MOZAMBIK_METICALI_TL, 0)), 0)MOZAMBIK_METICALI_FARKI ,   " +
" MAX(NIJERYA_NAIRASI)NIJERYA_NAIRASIBAKIYE,MAX(NIJERYA_NAIRASI_TL)NIJERYA_NAIRASI_TLBAKIYE,ISNULL(MAX((NIJERYA_NAIRASI * DOVIZKUR) - ISNULL(NIJERYA_NAIRASI_TL, 0)), 0)NIJERYA_NAIRASI_FARKI ,   " +
" MAX(NIKARAGUA_CORDOBA_OROSU)NIKARAGUA_CORDOBA_OROSUBAKIYE,MAX(NIKARAGUA_CORDOBA_OROSU_TL)NIKARAGUA_CORDOBA_OROSU_TLBAKIYE,ISNULL(MAX((NIKARAGUA_CORDOBA_OROSU * DOVIZKUR) - ISNULL(NIKARAGUA_CORDOBA_OROSU_TL, 0)), 0)NIKARAGUA_CORDOBA_OROSU_FARKI ,   " +
" MAX(NEPAL_RUPISI)NEPAL_RUPISIBAKIYE,MAX(NEPAL_RUPISI_TL)NEPAL_RUPISI_TLBAKIYE,ISNULL(MAX((NEPAL_RUPISI * DOVIZKUR) - ISNULL(NEPAL_RUPISI_TL, 0)), 0)NEPAL_RUPISI_FARKI ,   " +
" MAX(YENI_ZELANDA_DOLARI)YENI_ZELANDA_DOLARIBAKIYE,MAX(YENI_ZELANDA_DOLARI_TL)YENI_ZELANDA_DOLARI_TLBAKIYE,ISNULL(MAX((YENI_ZELANDA_DOLARI * DOVIZKUR) - ISNULL(YENI_ZELANDA_DOLARI_TL, 0)), 0)YENI_ZELANDA_DOLARI_FARKI ,   " +
" MAX(UMMAN_RIYALI)UMMAN_RIYALIBAKIYE,MAX(UMMAN_RIYALI_TL)UMMAN_RIYALI_TLBAKIYE,ISNULL(MAX((UMMAN_RIYALI * DOVIZKUR) - ISNULL(UMMAN_RIYALI_TL, 0)), 0)UMMAN_RIYALI_FARKI ,   " +
" MAX(PANAMA_BALBOASI)PANAMA_BALBOASIBAKIYE,MAX(PANAMA_BALBOASI_TL)PANAMA_BALBOASI_TLBAKIYE,ISNULL(MAX((PANAMA_BALBOASI * DOVIZKUR) - ISNULL(PANAMA_BALBOASI_TL, 0)), 0)PANAMA_BALBOASI_FARKI ,   " +
" MAX(PERU_SOLU)PERU_SOLUBAKIYE,MAX(PERU_SOLU_TL)PERU_SOLU_TLBAKIYE,ISNULL(MAX((PERU_SOLU * DOVIZKUR) - ISNULL(PERU_SOLU_TL, 0)), 0)PERU_SOLU_FARKI ,   " +
" MAX(PAPUA_YENI_GINE_KINASI)PAPUA_YENI_GINE_KINASIBAKIYE,MAX(PAPUA_YENI_GINE_KINASI_TL)PAPUA_YENI_GINE_KINASI_TLBAKIYE,ISNULL(MAX((PAPUA_YENI_GINE_KINASI * DOVIZKUR) - ISNULL(PAPUA_YENI_GINE_KINASI_TL, 0)), 0)PAPUA_YENI_GINE_KINASI_FARKI ,   " +
" MAX(FILIPIN_PESOSU)FILIPIN_PESOSUBAKIYE,MAX(FILIPIN_PESOSU_TL)FILIPIN_PESOSU_TLBAKIYE,ISNULL(MAX((FILIPIN_PESOSU * DOVIZKUR) - ISNULL(FILIPIN_PESOSU_TL, 0)), 0)FILIPIN_PESOSU_FARKI ,   " +
" MAX(PAKISTAN_RUPISI)PAKISTAN_RUPISIBAKIYE,MAX(PAKISTAN_RUPISI_TL)PAKISTAN_RUPISI_TLBAKIYE,ISNULL(MAX((PAKISTAN_RUPISI * DOVIZKUR) - ISNULL(PAKISTAN_RUPISI_TL, 0)), 0)PAKISTAN_RUPISI_FARKI ,   " +
" MAX(PARAGUAY_GUARANISI)PARAGUAY_GUARANISIBAKIYE,MAX(PARAGUAY_GUARANISI_TL)PARAGUAY_GUARANISI_TLBAKIYE,ISNULL(MAX((PARAGUAY_GUARANISI * DOVIZKUR) - ISNULL(PARAGUAY_GUARANISI_TL, 0)), 0)PARAGUAY_GUARANISI_FARKI ,   " +
" MAX(KATAR_RIYALI)KATAR_RIYALIBAKIYE,MAX(KATAR_RIYALI_TL)KATAR_RIYALI_TLBAKIYE,ISNULL(MAX((KATAR_RIYALI * DOVIZKUR) - ISNULL(KATAR_RIYALI_TL, 0)), 0)KATAR_RIYALI_FARKI ,   " +
" MAX(RUANDA_FRANGI)RUANDA_FRANGIBAKIYE,MAX(RUANDA_FRANGI_TL)RUANDA_FRANGI_TLBAKIYE,ISNULL(MAX((RUANDA_FRANGI * DOVIZKUR) - ISNULL(RUANDA_FRANGI_TL, 0)), 0)RUANDA_FRANGI_FARKI ,   " +
" MAX(SOLOMON_ADALARI_DOLARI)SOLOMON_ADALARI_DOLARIBAKIYE,MAX(SOLOMON_ADALARI_DOLARI_TL)SOLOMON_ADALARI_DOLARI_TLBAKIYE,ISNULL(MAX((SOLOMON_ADALARI_DOLARI * DOVIZKUR) - ISNULL(SOLOMON_ADALARI_DOLARI_TL, 0)), 0)SOLOMON_ADALARI_DOLARI_FARKI ,   " +
" MAX(SEYSEL_ADALARI_RUPISI)SEYSEL_ADALARI_RUPISIBAKIYE,MAX(SEYSEL_ADALARI_RUPISI_TL)SEYSEL_ADALARI_RUPISI_TLBAKIYE,ISNULL(MAX((SEYSEL_ADALARI_RUPISI * DOVIZKUR) - ISNULL(SEYSEL_ADALARI_RUPISI_TL, 0)), 0)SEYSEL_ADALARI_RUPISI_FARKI ,   " +
" MAX(SUDAN_DINARI)SUDAN_DINARIBAKIYE,MAX(SUDAN_DINARI_TL)SUDAN_DINARI_TLBAKIYE,ISNULL(MAX((SUDAN_DINARI * DOVIZKUR) - ISNULL(SUDAN_DINARI_TL, 0)), 0)SUDAN_DINARI_FARKI ,   " +
" MAX(SINGAPUR_DOLARI)SINGAPUR_DOLARIBAKIYE,MAX(SINGAPUR_DOLARI_TL)SINGAPUR_DOLARI_TLBAKIYE,ISNULL(MAX((SINGAPUR_DOLARI * DOVIZKUR) - ISNULL(SINGAPUR_DOLARI_TL, 0)), 0)SINGAPUR_DOLARI_FARKI ,   " +
" MAX(ST_HELEN_LIRASI)ST_HELEN_LIRASIBAKIYE,MAX(ST_HELEN_LIRASI_TL)ST_HELEN_LIRASI_TLBAKIYE,ISNULL(MAX((ST_HELEN_LIRASI * DOVIZKUR) - ISNULL(ST_HELEN_LIRASI_TL, 0)), 0)ST_HELEN_LIRASI_FARKI ,   " +
" MAX(SIERRA_LEONE_LEONESI)SIERRA_LEONE_LEONESIBAKIYE,MAX(SIERRA_LEONE_LEONESI_TL)SIERRA_LEONE_LEONESI_TLBAKIYE,ISNULL(MAX((SIERRA_LEONE_LEONESI * DOVIZKUR) - ISNULL(SIERRA_LEONE_LEONESI_TL, 0)), 0)SIERRA_LEONE_LEONESI_FARKI ,   " +
" MAX(SOMALI_SILINI)SOMALI_SILINIBAKIYE,MAX(SOMALI_SILINI_TL)SOMALI_SILINI_TLBAKIYE,ISNULL(MAX((SOMALI_SILINI * DOVIZKUR) - ISNULL(SOMALI_SILINI_TL, 0)), 0)SOMALI_SILINI_FARKI ,   " +
" MAX(SURINAM_FLORINI)SURINAM_FLORINIBAKIYE,MAX(SURINAM_FLORINI_TL)SURINAM_FLORINI_TLBAKIYE,ISNULL(MAX((SURINAM_FLORINI * DOVIZKUR) - ISNULL(SURINAM_FLORINI_TL, 0)), 0)SURINAM_FLORINI_FARKI ,   " +
" MAX(SAO_TOME_DOBRASI)SAO_TOME_DOBRASIBAKIYE,MAX(SAO_TOME_DOBRASI_TL)SAO_TOME_DOBRASI_TLBAKIYE,ISNULL(MAX((SAO_TOME_DOBRASI * DOVIZKUR) - ISNULL(SAO_TOME_DOBRASI_TL, 0)), 0)SAO_TOME_DOBRASI_FARKI ,   " +
" MAX(EL_SALVADOR_COLONU)EL_SALVADOR_COLONUBAKIYE,MAX(EL_SALVADOR_COLONU_TL)EL_SALVADOR_COLONU_TLBAKIYE,ISNULL(MAX((EL_SALVADOR_COLONU * DOVIZKUR) - ISNULL(EL_SALVADOR_COLONU_TL, 0)), 0)EL_SALVADOR_COLONU_FARKI ,   " +
" MAX(SURIYE_LIRASI)SURIYE_LIRASIBAKIYE,MAX(SURIYE_LIRASI_TL)SURIYE_LIRASI_TLBAKIYE,ISNULL(MAX((SURIYE_LIRASI * DOVIZKUR) - ISNULL(SURIYE_LIRASI_TL, 0)), 0)SURIYE_LIRASI_FARKI ,   " +
" MAX(SWAZILAND_LILANGENISI)SWAZILAND_LILANGENISIBAKIYE,MAX(SWAZILAND_LILANGENISI_TL)SWAZILAND_LILANGENISI_TLBAKIYE,ISNULL(MAX((SWAZILAND_LILANGENISI * DOVIZKUR) - ISNULL(SWAZILAND_LILANGENISI_TL, 0)), 0)SWAZILAND_LILANGENISI_FARKI ,   " +
" MAX(TAYLAND_BAHTI)TAYLAND_BAHTIBAKIYE,MAX(TAYLAND_BAHTI_TL)TAYLAND_BAHTI_TLBAKIYE,ISNULL(MAX((TAYLAND_BAHTI * DOVIZKUR) - ISNULL(TAYLAND_BAHTI_TL, 0)), 0)TAYLAND_BAHTI_FARKI ,   " +
" MAX(TUNUS_DINARI)TUNUS_DINARIBAKIYE,MAX(TUNUS_DINARI_TL)TUNUS_DINARI_TLBAKIYE,ISNULL(MAX((TUNUS_DINARI * DOVIZKUR) - ISNULL(TUNUS_DINARI_TL, 0)), 0)TUNUS_DINARI_FARKI ,   " +
" MAX(DOGU_TIMOR_ESKUDOSU)DOGU_TIMOR_ESKUDOSUBAKIYE,MAX(DOGU_TIMOR_ESKUDOSU_TL)DOGU_TIMOR_ESKUDOSU_TLBAKIYE,ISNULL(MAX((DOGU_TIMOR_ESKUDOSU * DOVIZKUR) - ISNULL(DOGU_TIMOR_ESKUDOSU_TL, 0)), 0)DOGU_TIMOR_ESKUDOSU_FARKI ,   " +
" MAX(TRINIDAD_VE_TOBAGO_DOLARI)TRINIDAD_VE_TOBAGO_DOLARIBAKIYE,MAX(TRINIDAD_VE_TOBAGO_DOLARI_TL)TRINIDAD_VE_TOBAGO_DOLARI_TLBAKIYE,ISNULL(MAX((TRINIDAD_VE_TOBAGO_DOLARI * DOVIZKUR) - ISNULL(TRINIDAD_VE_TOBAGO_DOLARI_TL, 0)), 0)TRINIDAD_VE_TOBAGO_DOLARI_FARKI ,   " +
" MAX(TANZANYA_SILINI)TANZANYA_SILINIBAKIYE,MAX(TANZANYA_SILINI_TL)TANZANYA_SILINI_TLBAKIYE,ISNULL(MAX((TANZANYA_SILINI * DOVIZKUR) - ISNULL(TANZANYA_SILINI_TL, 0)), 0)TANZANYA_SILINI_FARKI ,   " +
" MAX(UGANDA_SILINI)UGANDA_SILINIBAKIYE,MAX(UGANDA_SILINI_TL)UGANDA_SILINI_TLBAKIYE,ISNULL(MAX((UGANDA_SILINI * DOVIZKUR) - ISNULL(UGANDA_SILINI_TL, 0)), 0)UGANDA_SILINI_FARKI ,   " +
" MAX(URUGUAY_PESOSU)URUGUAY_PESOSUBAKIYE,MAX(URUGUAY_PESOSU_TL)URUGUAY_PESOSU_TLBAKIYE,ISNULL(MAX((URUGUAY_PESOSU * DOVIZKUR) - ISNULL(URUGUAY_PESOSU_TL, 0)), 0)URUGUAY_PESOSU_FARKI ,   " +
" MAX(VENEZUELLA_BOLIVARI)VENEZUELLA_BOLIVARIBAKIYE,MAX(VENEZUELLA_BOLIVARI_TL)VENEZUELLA_BOLIVARI_TLBAKIYE,ISNULL(MAX((VENEZUELLA_BOLIVARI * DOVIZKUR) - ISNULL(VENEZUELLA_BOLIVARI_TL, 0)), 0)VENEZUELLA_BOLIVARI_FARKI ,   " +
" MAX(VIETNAM_DONGU)VIETNAM_DONGUBAKIYE,MAX(VIETNAM_DONGU_TL)VIETNAM_DONGU_TLBAKIYE,ISNULL(MAX((VIETNAM_DONGU * DOVIZKUR) - ISNULL(VIETNAM_DONGU_TL, 0)), 0)VIETNAM_DONGU_FARKI ,   " +
" MAX(SAMOA_TALASI)SAMOA_TALASIBAKIYE,MAX(SAMOA_TALASI_TL)SAMOA_TALASI_TLBAKIYE,ISNULL(MAX((SAMOA_TALASI * DOVIZKUR) - ISNULL(SAMOA_TALASI_TL, 0)), 0)SAMOA_TALASI_FARKI ,   " +
" MAX(YEMEN_DINARI)YEMEN_DINARIBAKIYE,MAX(YEMEN_DINARI_TL)YEMEN_DINARI_TLBAKIYE,ISNULL(MAX((YEMEN_DINARI * DOVIZKUR) - ISNULL(YEMEN_DINARI_TL, 0)), 0)YEMEN_DINARI_FARKI ,   " +
" MAX(YEMEN_RIYALI)YEMEN_RIYALIBAKIYE,MAX(YEMEN_RIYALI_TL)YEMEN_RIYALI_TLBAKIYE,ISNULL(MAX((YEMEN_RIYALI * DOVIZKUR) - ISNULL(YEMEN_RIYALI_TL, 0)), 0)YEMEN_RIYALI_FARKI ,   " +
" MAX(YUGOSLAV_DINARI)YUGOSLAV_DINARIBAKIYE,MAX(YUGOSLAV_DINARI_TL)YUGOSLAV_DINARI_TLBAKIYE,ISNULL(MAX((YUGOSLAV_DINARI * DOVIZKUR) - ISNULL(YUGOSLAV_DINARI_TL, 0)), 0)YUGOSLAV_DINARI_FARKI ,   " +
" MAX(GUNEY_AFRIKA_RANDI)GUNEY_AFRIKA_RANDIBAKIYE,MAX(GUNEY_AFRIKA_RANDI_TL)GUNEY_AFRIKA_RANDI_TLBAKIYE,ISNULL(MAX((GUNEY_AFRIKA_RANDI * DOVIZKUR) - ISNULL(GUNEY_AFRIKA_RANDI_TL, 0)), 0)GUNEY_AFRIKA_RANDI_FARKI ,   " +
" MAX(ZAMBIA_KWACHASI)ZAMBIA_KWACHASIBAKIYE,MAX(ZAMBIA_KWACHASI_TL)ZAMBIA_KWACHASI_TLBAKIYE,ISNULL(MAX((ZAMBIA_KWACHASI * DOVIZKUR) - ISNULL(ZAMBIA_KWACHASI_TL, 0)), 0)ZAMBIA_KWACHASI_FARKI ,   " +
" MAX(ZIMBABWE_DOLARI)ZIMBABWE_DOLARIBAKIYE,MAX(ZIMBABWE_DOLARI_TL)ZIMBABWE_DOLARI_TLBAKIYE,ISNULL(MAX((ZIMBABWE_DOLARI * DOVIZKUR) - ISNULL(ZIMBABWE_DOLARI_TL, 0)), 0)ZIMBABWE_DOLARI_FARKI ,   " +
" MAX(KAZAK_TENGESI)KAZAK_TENGESIBAKIYE,MAX(KAZAK_TENGESI_TL)KAZAK_TENGESI_TLBAKIYE,ISNULL(MAX((KAZAK_TENGESI * DOVIZKUR) - ISNULL(KAZAK_TENGESI_TL, 0)), 0)KAZAK_TENGESI_FARKI ,   " +
" MAX(UKRAYNA_GREVNIYASI)UKRAYNA_GREVNIYASIBAKIYE,MAX(UKRAYNA_GREVNIYASI_TL)UKRAYNA_GREVNIYASI_TLBAKIYE,ISNULL(MAX((UKRAYNA_GREVNIYASI * DOVIZKUR) - ISNULL(UKRAYNA_GREVNIYASI_TL, 0)), 0)UKRAYNA_GREVNIYASI_FARKI ,   " +
" MAX(TURKMENISTAN_MANATI)TURKMENISTAN_MANATIBAKIYE,MAX(TURKMENISTAN_MANATI_TL)TURKMENISTAN_MANATI_TLBAKIYE,ISNULL(MAX((TURKMENISTAN_MANATI * DOVIZKUR) - ISNULL(TURKMENISTAN_MANATI_TL, 0)), 0)TURKMENISTAN_MANATI_FARKI ,   " +
" MAX(OZBEKISTAN_SOMU)OZBEKISTAN_SOMUBAKIYE,MAX(OZBEKISTAN_SOMU_TL)OZBEKISTAN_SOMU_TLBAKIYE,ISNULL(MAX((OZBEKISTAN_SOMU * DOVIZKUR) - ISNULL(OZBEKISTAN_SOMU_TL, 0)), 0)OZBEKISTAN_SOMU_FARKI ,   " +
" MAX(ROMEN_YENI_LEYI)ROMEN_YENI_LEYIBAKIYE,MAX(ROMEN_YENI_LEYI_TL)ROMEN_YENI_LEYI_TLBAKIYE,ISNULL(MAX((ROMEN_YENI_LEYI * DOVIZKUR) - ISNULL(ROMEN_YENI_LEYI_TL, 0)), 0)ROMEN_YENI_LEYI_FARKI ,   " +
" MAX(AZERBAYCAN_YENI_MANATI)AZERBAYCAN_YENI_MANATIBAKIYE,MAX(AZERBAYCAN_YENI_MANATI_TL)AZERBAYCAN_YENI_MANATI_TLBAKIYE,ISNULL(MAX((AZERBAYCAN_YENI_MANATI * DOVIZKUR) - ISNULL(AZERBAYCAN_YENI_MANATI_TL, 0)), 0)AZERBAYCAN_YENI_MANATI_FARKI " +
" FROM(  " +
" SELECT MAX(CLC.CODE) Kod, MAX(CLC.DEFINITION_) Unvan " +
"  , ISNULL(MAX(L.CURCODE), 'TL')[DVZ] " +
"     , CASE WHEN  CLFL.TRCURR IN(0, 160) THEN 'TL' WHEN  CLFL.TRCURR IN(1) THEN 'USD' WHEN  CLFL.TRCURR IN(20) THEN 'EUR' END  DOVIZ " +
"     , (SELECT TOP 1 RATES1  FROM[" + AnaForm.db +  "].[dbo].LG_EXCHANGE_" + AnaForm.firma +  " WHERE EDATE <= GETDATE()  AND CRTYPE = MAX(CLFL.TRCURR) ORDER BY EDATE DESC) DOVIZKUR " +
"     ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(1) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET " +
" ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[DOLAR] " +
"     ,ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(1) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[DOLARTL] " +
"     ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(20) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET " +
" ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[EURO] " +
"     ,ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(20) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[EUROTL] " +
"  ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(2) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[ALMAN_MARKI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(2) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[ALMAN_MARKI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(3) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[AVUSTRALYA_DOLARI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(3) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[AVUSTRALYA_DOLARI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(4) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[AVUSTURYA_SILINI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(4) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[AVUSTURYA_SILINI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(5) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[BELCIKA_FRANGI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(5) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[BELCIKA_FRANGI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(6) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[DANIMARKA_KRONU], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(6) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[DANIMARKA_KRONU_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(7) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[FIN_MARKKASI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(7) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[FIN_MARKKASI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(8) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[FRANSIZ_FRANGI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(8) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[FRANSIZ_FRANGI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(9) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[HOLLANDA_FLORINI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(9) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[HOLLANDA_FLORINI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(10) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[ISVEC_KRONU], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(10) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[ISVEC_KRONU_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(11) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[ISVICRE_FRANGI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(11) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[ISVICRE_FRANGI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(12) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[ITALYAN_LIRETI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(12) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[ITALYAN_LIRETI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(13) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[JAPON_YENI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(13) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[JAPON_YENI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(14) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[KANADA_DOLARI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(14) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[KANADA_DOLARI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(15) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[KUVEYT_DINARI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(15) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[KUVEYT_DINARI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(16) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[NORVEC_KRONU], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(16) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[NORVEC_KRONU_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(17) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[INGILIZ_STERLINI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(17) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[INGILIZ_STERLINI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(18) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[S_ARABISTAN_RIYALI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(18) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[S_ARABISTAN_RIYALI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(19) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[AVRUPA_PARA_BIRIMI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(19) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[AVRUPA_PARA_BIRIMI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(21) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[AZERBAYCAN_MANATI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(21) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[AZERBAYCAN_MANATI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(22) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[BREZILYA_CRUZEIROSU], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(22) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[BREZILYA_CRUZEIROSU_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(23) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[BULGAR_LEVASI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(23) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[BULGAR_LEVASI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(24) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[CEK_KURONU], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(24) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[CEK_KURONU_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(25) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[CIN_YUENI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(25) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[CIN_YUENI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(26) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[ESTONYA_KURONU], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(26) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[ESTONYA_KURONU_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(27) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[GURCISTAN_LARISI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(27) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[GURCISTAN_LARISI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(28) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[HINDISTAN_RUPISI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(28) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[HINDISTAN_RUPISI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(29) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[HONGKONG_DOLARI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(29) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[HONGKONG_DOLARI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(30) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[IRAK_DINARI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(30) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[IRAK_DINARI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(31) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[IRAN_RIYALI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(31) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[IRAN_RIYALI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(32) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[IRLANDA_LIRASI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(32) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[IRLANDA_LIRASI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(33) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[ISPANYOL_PESETASI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(33) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[ISPANYOL_PESETASI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(34) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[ISRAIL_SEKELI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(34) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[ISRAIL_SEKELI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(35) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[IZLANDA_KURONU], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(35) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[IZLANDA_KURONU_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(36) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[KIBRIS_LIRASI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(36) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[KIBRIS_LIRASI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(37) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[KIRGIZISTAN_SOMU], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(37) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[KIRGIZISTAN_SOMU_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(38) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[LETONYA_LATSI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(38) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[LETONYA_LATSI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(39) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[LIBYA_DINARI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(39) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[LIBYA_DINARI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(40) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[LUBNAN_LIRASI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(40) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[LUBNAN_LIRASI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(41) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[LITVANYA_LITASI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(41) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[LITVANYA_LITASI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(42) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[LUKSEMBURG_FRANGI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(42) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[LUKSEMBURG_FRANGI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(43) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[MACARISTAN_FORINTI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(43) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[MACARISTAN_FORINTI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(44) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[MALEZYA_RINGGITI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(44) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[MALEZYA_RINGGITI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(45) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[MEKSIKA_PESOSU], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(45) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[MEKSIKA_PESOSU_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(46) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[MISIR_LIRASI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(46) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[MISIR_LIRASI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(47) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[BARBADOS_DOLARI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(47) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[BARBADOS_DOLARI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(48) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[POLONYA_ZLOTISI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(48) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[POLONYA_ZLOTISI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(49) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[PORTEKIZ_ESCUDOSU], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(49) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[PORTEKIZ_ESCUDOSU_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(50) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[ROMEN_LEYI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(50) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[ROMEN_LEYI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(51) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[RUS_RUBLESI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(51) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[RUS_RUBLESI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(52) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[TAYVAN_DOLARI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(52) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[TAYVAN_DOLARI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(53) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[TURK_LIRASI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(53) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[TURK_LIRASI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(54) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[URDUN_DINARI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(54) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[URDUN_DINARI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(55) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[YUNAN_DRAHMISI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(55) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[YUNAN_DRAHMISI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(56) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[ARJANTIN_PESOSU], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(56) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[ARJANTIN_PESOSU_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(57) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[LAOS_KIPI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(57) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[LAOS_KIPI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(58) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[ANDORRA_PESETASI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(58) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[ANDORRA_PESETASI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(59) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[BAE_DIRHEMI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(59) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[BAE_DIRHEMI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(60) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[AFGANISTAN_AFGANISI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(60) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[AFGANISTAN_AFGANISI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(61) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[ARNAVUTLUK_LEKI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(61) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[ARNAVUTLUK_LEKI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(62) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[HOLLANDA_ANTILLERI_FLORINI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(62) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[HOLLANDA_ANTILLERI_FLORINI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(63) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[ANGOLA_KWANZASI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(63) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[ANGOLA_KWANZASI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(64) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[BENGALDES_TAKASI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(64) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[BENGALDES_TAKASI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(65) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[BAHREYN_DINARI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(65) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[BAHREYN_DINARI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(66) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[BURUNDI_FRANGI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(66) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[BURUNDI_FRANGI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(67) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[BERMUDA_DOLARI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(67) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[BERMUDA_DOLARI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(68) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[BRUNEI_DOLARI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(68) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[BRUNEI_DOLARI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(69) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[BOLIVYA_BOLIVIANOSU], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(69) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[BOLIVYA_BOLIVIANOSU_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(70) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[BAHAMA_DOLARI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(70) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[BAHAMA_DOLARI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(71) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[BUTAN_LIRASI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(71) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[BUTAN_LIRASI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(72) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[BOTSWANA_PULASI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(72) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[BOTSWANA_PULASI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(73) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[BELIZE_DOLARI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(73) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[BELIZE_DOLARI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(74) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[SILI_PESOSU], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(74) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[SILI_PESOSU_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(75) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[KOLOMBIYA_PESOSU], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(75) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[KOLOMBIYA_PESOSU_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(76) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[KOSTA_RIKA_KOLONU], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(76) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[KOSTA_RIKA_KOLONU_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(77) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[KUBA_PESOSU], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(77) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[KUBA_PESOSU_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(78) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[CAPE_VERDE_ESKUDOSU], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(78) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[CAPE_VERDE_ESKUDOSU_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(79) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[CIBUTI_FRANGI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(79) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[CIBUTI_FRANGI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(80) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[DOMINIK_PESOSU], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(80) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[DOMINIK_PESOSU_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(81) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[CEZAYIR_DINARI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(81) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[CEZAYIR_DINARI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(82) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[EKVATOR_SUCRESI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(82) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[EKVATOR_SUCRESI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(83) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[ETYOPYA_BIRRI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(83) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[ETYOPYA_BIRRI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(84) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[FIJI_ADALARI_DOLARI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(84) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[FIJI_ADALARI_DOLARI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(85) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[FALKLAND_ADALARI_STERLINI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(85) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[FALKLAND_ADALARI_STERLINI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(86) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[GANA_CEDISI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(86) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[GANA_CEDISI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(87) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[CEBELITARIK_STERLINI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(87) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[CEBELITARIK_STERLINI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(88) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[GAMBIA_DALASISI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(88) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[GAMBIA_DALASISI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(89) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[GINE_FRANGI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(89) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[GINE_FRANGI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(90) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[GUATEMALA_QUETZALI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(90) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[GUATEMALA_QUETZALI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(91) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[GINEBISSE_PESOSU], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(91) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[GINEBISSE_PESOSU_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(92) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[GUYANA_DOLARI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(92) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[GUYANA_DOLARI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(93) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[HONDURAS_LEMPIRASI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(93) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[HONDURAS_LEMPIRASI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(94) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[HAITI_GOURDESI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(94) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[HAITI_GOURDESI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(95) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[ENDONEZYA_RUPISI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(95) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[ENDONEZYA_RUPISI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(96) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[JAMAIKA_DOLARI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(96) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[JAMAIKA_DOLARI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(97) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[KENYA_SILINGI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(97) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[KENYA_SILINGI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(98) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[KAMBOCYA_RIELI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(98) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[KAMBOCYA_RIELI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(99) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[KOMOR_FRANGI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(99) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[KOMOR_FRANGI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(100) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[KUZEY_KORE_WONU], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(100) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[KUZEY_KORE_WONU_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(101) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[GUNEY_KORE_WONU], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(101) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[GUNEY_KORE_WONU_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(102) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[CAYMAN_ADALARI_DOLARI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(102) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[CAYMAN_ADALARI_DOLARI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(103) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[SRI_LANKA_RUPISI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(103) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[SRI_LANKA_RUPISI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(104) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[LIBERYA_DOLARI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(104) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[LIBERYA_DOLARI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(105) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[LESOTO_LOTISI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(105) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[LESOTO_LOTISI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(106) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[FAS_DIRHEMI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(106) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[FAS_DIRHEMI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(107) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[MOGOL_TUGRIKI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(107) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[MOGOL_TUGRIKI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(108) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[MACAU_PATACASI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(108) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[MACAU_PATACASI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(109) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[MORITANYA_OGIYASI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(109) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[MORITANYA_OGIYASI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(110) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[MALTA_LIRASI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(110) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[MALTA_LIRASI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(111) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[MAURITIUS_RUPISI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(111) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[MAURITIUS_RUPISI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(112) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[MALDIV_RUFIYASI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(112) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[MALDIV_RUFIYASI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(113) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[MALAVI_KWACHASI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(113) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[MALAVI_KWACHASI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(114) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[MOZAMBIK_METICALI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(114) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[MOZAMBIK_METICALI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(115) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[NIJERYA_NAIRASI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(115) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[NIJERYA_NAIRASI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(116) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[NIKARAGUA_CORDOBA_OROSU], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(116) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[NIKARAGUA_CORDOBA_OROSU_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(117) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[NEPAL_RUPISI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(117) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[NEPAL_RUPISI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(118) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[YENI_ZELANDA_DOLARI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(118) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[YENI_ZELANDA_DOLARI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(119) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[UMMAN_RIYALI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(119) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[UMMAN_RIYALI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(120) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[PANAMA_BALBOASI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(120) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[PANAMA_BALBOASI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(121) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[PERU_SOLU], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(121) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[PERU_SOLU_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(122) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[PAPUA_YENI_GINE_KINASI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(122) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[PAPUA_YENI_GINE_KINASI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(123) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[FILIPIN_PESOSU], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(123) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[FILIPIN_PESOSU_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(124) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[PAKISTAN_RUPISI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(124) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[PAKISTAN_RUPISI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(125) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[PARAGUAY_GUARANISI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(125) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[PARAGUAY_GUARANISI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(126) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[KATAR_RIYALI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(126) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[KATAR_RIYALI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(127) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[RUANDA_FRANGI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(127) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[RUANDA_FRANGI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(128) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[SOLOMON_ADALARI_DOLARI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(128) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[SOLOMON_ADALARI_DOLARI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(129) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[SEYSEL_ADALARI_RUPISI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(129) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[SEYSEL_ADALARI_RUPISI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(130) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[SUDAN_DINARI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(130) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[SUDAN_DINARI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(131) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[SINGAPUR_DOLARI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(131) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[SINGAPUR_DOLARI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(132) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[ST_HELEN_LIRASI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(132) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[ST_HELEN_LIRASI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(133) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[SIERRA_LEONE_LEONESI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(133) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[SIERRA_LEONE_LEONESI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(134) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[SOMALI_SILINI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(134) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[SOMALI_SILINI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(135) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[SURINAM_FLORINI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(135) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[SURINAM_FLORINI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(136) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[SAO_TOME_DOBRASI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(136) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[SAO_TOME_DOBRASI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(137) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[EL_SALVADOR_COLONU], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(137) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[EL_SALVADOR_COLONU_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(138) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[SURIYE_LIRASI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(138) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[SURIYE_LIRASI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(139) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[SWAZILAND_LILANGENISI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(139) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[SWAZILAND_LILANGENISI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(140) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[TAYLAND_BAHTI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(140) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[TAYLAND_BAHTI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(141) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[TUNUS_DINARI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(141) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[TUNUS_DINARI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(142) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[DOGU_TIMOR_ESKUDOSU], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(142) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[DOGU_TIMOR_ESKUDOSU_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(143) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[TRINIDAD_VE_TOBAGO_DOLARI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(143) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[TRINIDAD_VE_TOBAGO_DOLARI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(144) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[TANZANYA_SILINI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(144) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[TANZANYA_SILINI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(145) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[UGANDA_SILINI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(145) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[UGANDA_SILINI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(146) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[URUGUAY_PESOSU], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(146) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[URUGUAY_PESOSU_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(147) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[VENEZUELLA_BOLIVARI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(147) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[VENEZUELLA_BOLIVARI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(148) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[VIETNAM_DONGU], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(148) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[VIETNAM_DONGU_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(149) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[SAMOA_TALASI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(149) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[SAMOA_TALASI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(150) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[YEMEN_DINARI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(150) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[YEMEN_DINARI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(151) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[YEMEN_RIYALI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(151) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[YEMEN_RIYALI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(152) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[YUGOSLAV_DINARI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(152) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[YUGOSLAV_DINARI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(153) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[GUNEY_AFRIKA_RANDI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(153) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[GUNEY_AFRIKA_RANDI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(154) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[ZAMBIA_KWACHASI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(154) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[ZAMBIA_KWACHASI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(155) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[ZIMBABWE_DOLARI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(155) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[ZIMBABWE_DOLARI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(156) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[KAZAK_TENGESI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(156) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[KAZAK_TENGESI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(157) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[UKRAYNA_GREVNIYASI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(157) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[UKRAYNA_GREVNIYASI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(158) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[TURKMENISTAN_MANATI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(158) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[TURKMENISTAN_MANATI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(159) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[OZBEKISTAN_SOMU], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(159) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[OZBEKISTAN_SOMU_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(161) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[ROMEN_YENI_LEYI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(161) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[ROMEN_YENI_LEYI_TL] " +
" ,ISNULL(SUM(CASE WHEN CLFL.TRCURR IN(162) THEN CASE WHEN CLFL.SIGN = 0 THEN CLFL.TRNET ELSE - CLFL.TRNET END ELSE 0 END), 0)  AS[AZERBAYCAN_YENI_MANATI], ISNULL(MAX(CASE WHEN CLFL.TRCURR IN(162) THEN TB.TLKARSILIK ELSE 0 END), 0)  AS[AZERBAYCAN_YENI_MANATI_TL] " +
" FROM  " + AnaForm.db +  ".dbo.LG_" + AnaForm.firma +  "_CLCARD(NOLOCK) CLC " +
" INNER JOIN " + AnaForm.db +  ".dbo.LG_" + AnaForm.firma +  "_" + AnaForm.donem +  "_CLFLINE CLFL(NoLock) ON CLC.LOGICALREF = CLFL.CLIENTREF " +
" LEFT JOIN " + AnaForm.db +  ".dbo.L_CURRENCYLIST L ON L.CURTYPE = CLFL.TRCURR AND L.FIRMNR = '" + AnaForm.firma +  "' " +
" LEFT JOIN(SELECT  CLFL.TRCURR, CLFL.CLIENTREF, ISNULL(MAX(PT.TOTALHEPSI), 0) + SUM(CASE WHEN CLFL.SIGN = 0 THEN CLFL.AMOUNT ELSE - CLFL.AMOUNT END)  AS[TLKARSILIK] " +
" FROM  " + AnaForm.db +  ".dbo.LG_" + AnaForm.firma +  "_" + AnaForm.donem +  "_CLFLINE CLFL(NoLock) " +
" LEFT JOIN(SELECT MAX(PT.CARDREF)CARDREF " +
"           , SUM(case when PT.SIGN = 0 THEN PT.TOTAL * (CASE WHEN PT.TRCURR IN(0,160) THEN 1 ELSE PT.TRRATE END) ELSE " +
" -PT.TOTAL * (CASE WHEN PT.TRCURR IN(0,160) THEN 1 ELSE PT.TRRATE END) END) AS[TOTALHEPSI] " +
" FROM  " + AnaForm.db +  ".dbo.LG_" + AnaForm.firma +  "_" + AnaForm.donem +  "_CLFLINE CLFL(NoLock)  " +
" LEFT JOIN " + AnaForm.db +  ".dbo.LG_" + AnaForm.firma +  "_" + AnaForm.donem +  "_PAYTRANS PT(NoLock) ON PT.CARDREF = CLFL.CLIENTREF " +
" WHERE PT.PAIDINCASH > 0 AND CLFL.CANCELLED = 0 AND CLFL.STATUS = 0 " +
" AND PT.MODULENR = CLFL.MODULENR " +
" AND(((CLFL.SOURCEFREF = PT.FICHEREF)AND PT.MODULENR<>5) OR((CLFL.LOGICALREF = PT.FICHEREF)AND PT.MODULENR<>4))  " +
" GROUP BY PT.CARDREF)PT ON PT.CARDREF = CLFL.CLIENTREF " +
" WHERE CLFL.CANCELLED = 0 AND CLFL.STATUS = 0 AND CLFL.DATE_ <= '" + AnaForm.bitisTarihi + "' " +
" GROUP BY CLFL.TRCURR,CLFL.CLIENTREF) TB ON TB.CLIENTREF = CLC.LOGICALREF AND TB.TRCURR = CLFL.TRCURR " +
" WHERE CLC.ACTIVE = 0 " +
" AND CLFL.CANCELLED = 0 " +
(AnaForm.dovizTuru!=""? " AND CLFL.TRCURR IN(" + AnaForm.dovizTuru + ") " :"" )+
" AND CLFL.DATE_ BETWEEN '"+AnaForm.baslangicTarihi  +"' AND '" + AnaForm.bitisTarihi + "' " +
 araSorgu +
" AND((1 = 1 " +
"  ) " +
"  ) " +
" GROUP BY CLC.LOGICALREF,CLFL.TRCURR " +
"   )A " +
" GROUP BY A.Kod,A.Unvan  " +
" ORDER BY A.Unvan; ";



            DataTable dt1 = new DataTable();
            SqlDataAdapter da = new SqlDataAdapter(sorgu3, bgl.baglanti());

            
            da.SelectCommand.CommandTimeout = 0;
            da.Fill(dt1);
            grid.DataSource = dt1;

           // AnaForm frm = new AnaForm();
          
             

           
        }

         
        protected override void DegiskenleriDoldur()
        {
            Tablo = tablo;
             
            BaseKartTuru = KartTuru.NumaralamaKontrol;
        }

          
    }
}